-- APG Matriculation Higher Secondary School content refresh.
-- Replaces the CMS starter content for the known demo pages and menu.
-- Contact submissions and media items outside med-1 through med-5 are preserved.
-- Review the project and take a database backup before applying to a live project.
BEGIN;

INSERT INTO site_settings (id, general, branding, seo, social_media, header, footer, updated_at)
VALUES (
  'default', '{"site_name":"APG Matriculation Higher Secondary School","site_title":"APG Matriculation Higher Secondary School | Learn, Grow, Shine","site_description":"A welcoming learning community in Ganapathy, Coimbatore, helping every student build knowledge, confidence and character.","logo_url":"","favicon_url":"data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"%3E%3Crect width=\"64\" height=\"64\" rx=\"16\" fill=\"%231e5631\"/%3E%3Cpath d=\"M14 25 32 14l18 11v24H14z\" fill=\"%23fff\"/%3E%3Cpath d=\"M25 49V34h14v15M20 28h24\" stroke=\"%23d59c37\" stroke-width=\"4\" fill=\"none\"/%3E%3C/svg%3E","website_url":"","contact_email":"","phone_number":"","address":"FCI Road, Ganapathy, Coimbatore"}'::jsonb, '{"primary_color":"#1e5631","secondary_color":"#16432a","accent_color":"#d59c37","font_family":"Plus Jakarta Sans","border_radius":"lg","dark_mode_enabled":false}'::jsonb,
  '{"site_title":"APG Matriculation Higher Secondary School | Learn, Grow, Shine","meta_description":"Discover APG Matriculation Higher Secondary School in Ganapathy, Coimbatore: academics, student life, admissions and campus information.","keywords":"APG school, matriculation school, higher secondary, Ganapathy, Coimbatore","og_image":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","social_sharing_title":"APG Matriculation Higher Secondary School","social_sharing_description":"A place to learn, grow and shine in Ganapathy, Coimbatore.","canonical_url":""}'::jsonb, '{"facebook":"","instagram":"","youtube":"","linkedin":"","twitter":"","whatsapp":""}'::jsonb,
  '{"layout":"standard","is_sticky":true,"show_cta":true,"cta_text":"Explore Admissions","cta_link":"/admissions","bg_style":"solid"}'::jsonb, '{"show_newsletter":false,"newsletter_title":"School Updates","newsletter_desc":"Keep up with school news and events.","copyright_text":"© 2026 APG Matriculation Higher Secondary School. All rights reserved.","show_social":false,"legal_links":[]}'::jsonb, NOW()
)
ON CONFLICT (id) DO UPDATE SET
  general = EXCLUDED.general,
  branding = EXCLUDED.branding,
  seo = EXCLUDED.seo,
  social_media = EXCLUDED.social_media,
  header = EXCLUDED.header,
  footer = EXCLUDED.footer,
  updated_at = NOW();

-- Remove legacy demo pages that have no APG equivalent.
DELETE FROM pages WHERE id IN ('page-services', 'page-projects', 'page-pricing');

INSERT INTO pages (id, title, slug, status, is_home, sort_order, seo, updated_at, published_at)
VALUES
  ('page-home', 'Home', '', 'published', TRUE, 0, '{"title":"APG Matriculation Higher Secondary School","description":"Welcome to APG Matriculation Higher Secondary School, FCI Road, Ganapathy, Coimbatore.","keywords":"APG Matriculation Higher Secondary School, Coimbatore","og_image":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","no_index":false}'::jsonb, NOW(), NOW()),
  ('page-about', 'About Us', 'about', 'published', FALSE, 1, '{"title":"About Us | APG Matriculation Higher Secondary School","description":"Learn about our school community, values and approach to learning.","keywords":"APG Matriculation Higher Secondary School, Coimbatore","og_image":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","no_index":false}'::jsonb, NOW(), NOW()),
  ('page-academics', 'Academics', 'academics', 'published', FALSE, 2, '{"title":"Academics | APG Matriculation Higher Secondary School","description":"Explore learning from foundational years through higher secondary.","keywords":"APG Matriculation Higher Secondary School, Coimbatore","og_image":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","no_index":false}'::jsonb, NOW(), NOW()),
  ('page-campus', 'Campus Life', 'campus-life', 'published', FALSE, 3, '{"title":"Campus Life | APG Matriculation Higher Secondary School","description":"Discover the activities, facilities and experiences that make school life rewarding.","keywords":"APG Matriculation Higher Secondary School, Coimbatore","og_image":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","no_index":false}'::jsonb, NOW(), NOW()),
  ('page-admissions', 'Admissions', 'admissions', 'published', FALSE, 4, '{"title":"Admissions | APG Matriculation Higher Secondary School","description":"Find out how to enquire about admissions at APG Matriculation Higher Secondary School.","keywords":"APG Matriculation Higher Secondary School, Coimbatore","og_image":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","no_index":false}'::jsonb, NOW(), NOW()),
  ('page-contact', 'Contact Us', 'contact', 'published', FALSE, 5, '{"title":"Contact Us | APG Matriculation Higher Secondary School","description":"Get in touch or find our campus at FCI Road, Ganapathy, Coimbatore.","keywords":"APG Matriculation Higher Secondary School, Coimbatore","og_image":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","no_index":false}'::jsonb, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  status = EXCLUDED.status,
  is_home = EXCLUDED.is_home,
  sort_order = EXCLUDED.sort_order,
  seo = EXCLUDED.seo,
  updated_at = NOW(),
  published_at = NOW();

-- These are the page contents being replaced by the APG starter layout.
DELETE FROM page_sections WHERE page_id IN ('page-home', 'page-about', 'page-academics', 'page-campus', 'page-admissions', 'page-contact', 'page-services', 'page-projects', 'page-pricing');

INSERT INTO page_sections (id, page_id, section_type, content, settings, sort_order, is_visible, created_at, updated_at)
VALUES
  ('home-hero', 'page-home', 'hero', '{"badge":"Welcome to APG School","heading":"A bright beginning for every learner","description":"At APG Matriculation Higher Secondary School, we nurture curiosity, confidence and a lifelong love of learning. Visit us on FCI Road, Ganapathy, Coimbatore.","primary_btn_text":"Discover Our School","primary_btn_link":"/about","secondary_btn_text":"Admissions Enquiry","secondary_btn_link":"/admissions","image_url":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","stats":[{"label":"Learning","value":"Every day"},{"label":"Our community","value":"Growing together"},{"label":"Location","value":"Coimbatore"}]}'::jsonb, '{"background_style":"gradient","padding_y":"spacious","alignment":"center"}'::jsonb, 0, TRUE, NOW(), NOW()),
  ('home-values', 'page-home', 'bento_grid', '{"badge":"The APG Experience","heading":"Room to learn. Support to thrive.","description":"A school experience built around strong foundations, thoughtful guidance and opportunities to explore.","items":[{"title":"Strong foundations","desc":"Build understanding and confidence through a supportive learning environment.","icon":"Layers","badge":"Learning"},{"title":"Curious minds","desc":"Encourage questions, discovery and a habit of learning beyond the classroom.","icon":"Sparkles","badge":"Explore"},{"title":"Character & care","desc":"Grow respect, responsibility and kindness as part of everyday school life.","icon":"Shield","badge":"Values"},{"title":"A place to belong","desc":"Help every child feel welcomed, known and encouraged to do their best.","icon":"Activity","badge":"Community"}]}'::jsonb, '{"background_style":"dark","padding_y":"spacious","alignment":"center"}'::jsonb, 1, TRUE, NOW(), NOW()),
  ('home-about', 'page-home', 'about', '{"badge":"Who We Are","heading":"Learning with purpose, growing with confidence","description":"APG Matriculation Higher Secondary School is a learning community serving families in Ganapathy, Coimbatore. We aim to help students develop academically and personally, with care, encouragement and a sense of belonging.","image_url":"https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=85","points":["A welcoming and supportive school community","Learning that builds strong foundations","Encouragement to explore interests and talents","A focus on confidence, respect and responsibility"],"cta_text":"More About APG","cta_link":"/about"}'::jsonb, '{"background_style":"muted","padding_y":"spacious","alignment":"center"}'::jsonb, 2, TRUE, NOW(), NOW()),
  ('home-academics', 'page-home', 'services', '{"badge":"Learning at APG","heading":"Growing through every stage","description":"A broad school journey that supports students as their interests and abilities develop.","items":[{"title":"Foundational learning","desc":"Build confidence, communication and essential skills in the early years.","icon":"Sparkles"},{"title":"Middle school","desc":"Strengthen core subject knowledge and encourage independent thinking.","icon":"BookOpen"},{"title":"Secondary education","desc":"Develop focus, subject depth and readiness for the next step.","icon":"GraduationCap"},{"title":"Higher secondary","desc":"Support students as they pursue their academic goals and future plans.","icon":"Target"}]}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 3, TRUE, NOW(), NOW()),
  ('home-campus', 'page-home', 'projects', '{"badge":"A Day at School","heading":"More than lessons","description":"Learning also happens through discovery, creativity, friendship and shared experiences.","items":[{"title":"Learn together","category":"Classrooms","desc":"A positive space for participation, practice and new ideas.","image_url":"https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=85"},{"title":"Discover more","category":"Learning spaces","desc":"Encouraging reading, research and a curious outlook.","image_url":"https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=900&auto=format&fit=crop&q=85"},{"title":"Explore and experiment","category":"Hands-on learning","desc":"Make room for observation, questions and discovery.","image_url":"https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=900&auto=format&fit=crop&q=85"}]}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 4, TRUE, NOW(), NOW()),
  ('home-cta', 'page-home', 'cta', '{"heading":"Come and get to know APG","description":"We welcome families to learn more about our school and admissions. Find us at FCI Road, Ganapathy, Coimbatore.","primary_btn_text":"Admissions Enquiry","primary_btn_link":"/admissions","secondary_btn_text":"Contact the School","secondary_btn_link":"/contact"}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 5, TRUE, NOW(), NOW()),
  ('about-hero', 'page-about', 'hero', '{"badge":"About Our School","heading":"A community where every learner matters","description":"APG Matriculation Higher Secondary School is located at FCI Road, Ganapathy, Coimbatore. We believe children learn best when they feel supported, inspired and encouraged to take part.","image_url":"https://images.unsplash.com/photo-1529390079861-591de354faf5?w=900&auto=format&fit=crop&q=85","primary_btn_text":"Explore Academics","primary_btn_link":"/academics"}'::jsonb, '{"background_style":"gradient","padding_y":"spacious","alignment":"center"}'::jsonb, 0, TRUE, NOW(), NOW()),
  ('about-story', 'page-about', 'rich_text', '{"title":"Our approach","content":"<p>School is a place to discover strengths, ask questions and build the knowledge that opens new possibilities. At APG, we value consistent effort, thoughtful teaching and a caring relationship between students, families and educators.</p><p>We encourage students to take pride in their progress, respect one another and approach each new challenge with confidence.</p>"}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 1, TRUE, NOW(), NOW()),
  ('about-approach', 'page-about', 'bento_grid', '{"badge":"Our Values","heading":"Guided by care and high expectations","description":"The habits and values we practice help create a positive place to learn.","items":[{"title":"Respect","desc":"Listen, care for others and value different perspectives.","icon":"Shield"},{"title":"Curiosity","desc":"Ask questions and take an active part in learning.","icon":"Sparkles"},{"title":"Perseverance","desc":"Keep trying, learn from feedback and celebrate progress.","icon":"Activity"},{"title":"Responsibility","desc":"Take ownership of choices, learning and community.","icon":"CheckCircle"}]}'::jsonb, '{"background_style":"dark","padding_y":"spacious","alignment":"center"}'::jsonb, 2, TRUE, NOW(), NOW()),
  ('academics-hero', 'page-academics', 'hero', '{"badge":"Academics","heading":"A strong foundation for what comes next","description":"Learning at every stage is an opportunity to build understanding, independence and confidence.","image_url":"https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=85","primary_btn_text":"Ask About Admissions","primary_btn_link":"/admissions"}'::jsonb, '{"background_style":"gradient","padding_y":"spacious","alignment":"center"}'::jsonb, 0, TRUE, NOW(), NOW()),
  ('academics-programmes', 'page-academics', 'services', '{"badge":"Learning Journey","heading":"Support at every stage","description":"Our school brings students through a connected journey from early learning to higher secondary.","items":[{"title":"Primary years","desc":"Develop literacy, numeracy, communication and a positive approach to school.","icon":"BookOpen"},{"title":"Middle years","desc":"Broaden subject understanding and build strong study habits.","icon":"Layers"},{"title":"Secondary years","desc":"Deepen knowledge, apply ideas and prepare for important assessments.","icon":"Target"},{"title":"Higher secondary","desc":"Focus on chosen subjects and prepare for future study and career pathways.","icon":"GraduationCap"}]}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 1, TRUE, NOW(), NOW()),
  ('academics-note', 'page-academics', 'about', '{"badge":"Learning Together","heading":"Learning is a partnership","description":"Students make their best progress when school and home work together. We encourage regular attendance, open communication and a steady commitment to learning.","image_url":"https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=900&auto=format&fit=crop&q=85","points":["Regular attendance and a steady routine","Open communication between home and school","Encouragement to ask questions and seek support"],"cta_text":"Contact Our School","cta_link":"/contact"}'::jsonb, '{"background_style":"muted","padding_y":"spacious","alignment":"center"}'::jsonb, 2, TRUE, NOW(), NOW()),
  ('campus-hero', 'page-campus', 'hero', '{"badge":"Campus Life","heading":"A school day full of possibility","description":"Friendships, activities and new experiences help make each school day memorable.","image_url":"https://images.unsplash.com/photo-1529390079861-591de354faf5?w=900&auto=format&fit=crop&q=85","primary_btn_text":"Visit Our Campus","primary_btn_link":"/contact"}'::jsonb, '{"background_style":"gradient","padding_y":"spacious","alignment":"center"}'::jsonb, 0, TRUE, NOW(), NOW()),
  ('campus-gallery', 'page-campus', 'gallery', '{"badge":"Explore","heading":"Spaces to learn and grow","description":"A glimpse of the places and experiences that support learning and school life.","images":[{"title":"Classroom learning","url":"https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=85","category":"Learning"},{"title":"Reading and discovery","url":"https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=900&auto=format&fit=crop&q=85","category":"Learning"},{"title":"Science and exploration","url":"https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=900&auto=format&fit=crop&q=85","category":"Learning"},{"title":"Students learning together","url":"https://images.unsplash.com/photo-1529390079861-591de354faf5?w=900&auto=format&fit=crop&q=85","category":"Community"}]}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 1, TRUE, NOW(), NOW()),
  ('campus-life', 'page-campus', 'services', '{"badge":"Beyond the Classroom","heading":"Discover, participate, belong","description":"School life gives students opportunities to try new things and learn alongside one another.","items":[{"title":"Creative expression","desc":"Make space for imagination, ideas and self-expression.","icon":"Sparkles"},{"title":"Physical wellbeing","desc":"Encourage movement, teamwork and healthy habits.","icon":"Activity"},{"title":"Shared celebrations","desc":"Bring the school community together through events and traditions.","icon":"Globe"}]}'::jsonb, '{"background_style":"muted","padding_y":"spacious","alignment":"center"}'::jsonb, 2, TRUE, NOW(), NOW()),
  ('admissions-hero', 'page-admissions', 'hero', '{"badge":"Admissions","heading":"Begin your APG school journey","description":"We invite families to connect with us and learn about the admission process. Our campus is at FCI Road, Ganapathy, Coimbatore.","image_url":"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85","primary_btn_text":"Contact Admissions","primary_btn_link":"/contact","secondary_btn_text":"Explore Academics","secondary_btn_link":"/academics"}'::jsonb, '{"background_style":"gradient","padding_y":"spacious","alignment":"center"}'::jsonb, 0, TRUE, NOW(), NOW()),
  ('admissions-steps', 'page-admissions', 'services', '{"badge":"Getting Started","heading":"Three simple steps","description":"Our school team can guide you through the information you need.","items":[{"title":"Get in touch","desc":"Contact the school to share your child’s grade and ask your questions.","icon":"Phone"},{"title":"Visit and learn","desc":"Connect with our team to understand the school and its learning environment.","icon":"MapPin"},{"title":"Discuss next steps","desc":"Our team will explain the current application requirements and process.","icon":"CheckCircle"}]}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 1, TRUE, NOW(), NOW()),
  ('admissions-faq', 'page-admissions', 'faq', '{"badge":"Helpful Information","heading":"Admissions questions","description":"For current availability, documents and timings, please contact the school directly.","items":[{"question":"Where is the school located?","answer":"FCI Road, Ganapathy, Coimbatore."},{"question":"How can I ask about available classes?","answer":"Use the contact form or call the school office to discuss the current admissions availability."},{"question":"What documents are required?","answer":"Please contact the school office for the latest document checklist and application guidance."}]}'::jsonb, '{"background_style":"muted","padding_y":"spacious","alignment":"center"}'::jsonb, 2, TRUE, NOW(), NOW()),
  ('contact-hero', 'page-contact', 'hero', '{"badge":"Contact Us","heading":"We would love to hear from you","description":"Reach the school to ask a question, discuss admissions or arrange a visit. We are located at FCI Road, Ganapathy, Coimbatore."}'::jsonb, '{"background_style":"gradient","padding_y":"spacious","alignment":"center"}'::jsonb, 0, TRUE, NOW(), NOW()),
  ('contact-form', 'page-contact', 'contact_form', '{"badge":"Get in Touch","heading":"Send an enquiry","description":"Share your question and the school team will follow up.","address":"FCI Road, Ganapathy, Coimbatore","email":"","phone":"","hours":"Please contact the school for office hours."}'::jsonb, '{"background_style":"default","padding_y":"spacious","alignment":"center"}'::jsonb, 1, TRUE, NOW(), NOW());

-- The CMS navigation is replaced with the APG school menu.
DELETE FROM navigation_items;

INSERT INTO navigation_items (id, label, url, target, sort_order, is_visible, parent_id, created_at)
VALUES
  ('nav-home', 'Home', '/', '_self', 0, TRUE, NULL, NOW()),
  ('nav-about', 'About Us', '/about', '_self', 1, TRUE, NULL, NOW()),
  ('nav-academics', 'Academics', '/academics', '_self', 2, TRUE, NULL, NOW()),
  ('nav-campus', 'Campus Life', '/campus-life', '_self', 3, TRUE, NULL, NOW()),
  ('nav-admissions', 'Admissions', '/admissions', '_self', 4, TRUE, NULL, NOW()),
  ('nav-contact', 'Contact', '/contact', '_self', 5, TRUE, NULL, NOW());

-- Refresh the five built-in media records. Additional uploaded media is retained.
INSERT INTO media (id, name, url, type, size, format, alt_text, caption, created_at)
VALUES
  ('med-1', 'Students learning', 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&auto=format&fit=crop&q=85', 'image', 245000, 'image/jpeg', 'Students learning together at school', 'A welcoming school community', NOW()),
  ('med-2', 'Classroom', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=85', 'image', 310000, 'image/jpeg', 'Bright classroom with students', 'Classroom learning', NOW()),
  ('med-3', 'School library', 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=900&auto=format&fit=crop&q=85', 'image', 198000, 'image/jpeg', 'Bookshelves in a school library', 'Reading and discovery', NOW()),
  ('med-4', 'Science learning', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=900&auto=format&fit=crop&q=85', 'image', 215000, 'image/jpeg', 'Science learning and experimentation', 'Hands-on discovery', NOW()),
  ('med-5', 'Student community', 'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=900&auto=format&fit=crop&q=85', 'image', 215000, 'image/jpeg', 'Students learning and growing together', 'School life at APG', NOW())
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  url = EXCLUDED.url,
  type = EXCLUDED.type,
  size = EXCLUDED.size,
  format = EXCLUDED.format,
  alt_text = EXCLUDED.alt_text,
  caption = EXCLUDED.caption,
  created_at = NOW();

COMMIT;
